apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-client
spec:
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
      - name: client-container
        image: wanzetsemaloba/moringa-devops-04-ip2-ui:v0.1.1
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "250Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-client
spec:
  selector:
    app: client-app
  ports:
  - port: 3000
    targetPort: 3000

