apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ip4wan2stlfset
spec:
  selector:
    matchLabels:
      app: db-app
  serviceName: mongo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
      - name: db-app
        image: mongo
        ports:
        - containerPort: 27017
          name: db
        volumeMounts:
        - name: dbvol
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: dbvol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
