apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ip4_wan2_stlfset
spec:
  selector:
    matchLabels:
      app: db_app
  serviceName: mongo_service
  replicas: 1
  template:
    metadata:
      labels:
        app: db_app
    spec:
      containers:
      - name: db_app
        image: mongo
        ports:
        - containerPort: 27017
          name: db
        volumeMounts:
        - name: dbvol
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: dbvol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
