apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentserver
spec:
  selector:
    matchLabels:
      app: appserver
  template:
    metadata:
      labels:
        app: appserver
    spec:
      containers:
      - name: app-server-container2
        image: wanzetsemaloba/moringa-devops04-ip2-server:v0.0.2
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "250Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: app-service-server
spec:
  selector:
    app: app-server
  ports:
  - port: 5000
    targetPort: 5000

