name: moringa-devops-04-ip2-actions
run-name: ${{ github.actor }} Rebuid And push Docker Images
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: pull Current changes
        uses: actions/checkout@v4
      -
        name: Build Client Image
        run: docker build -t wanzetsemaloba/moringa-devops-04-ip2-ui:v0.1.1  ./client/Dockerfile
      -
        name: Build Server Image
        run: docker build -t wanzetsemaloba/moringa-devops-04-ip2-ui:v0.1.1  ./backend/Dockerfile
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Client Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: wanzetsemaloba/moringa-devops-04-ip2-ui:v0.1.1
      -
        name: Build and push Server Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: wanzetsemaloba/moringa-devops-04-ip2-ui:v0.1.1
      -
        name: Rebuild And Restart Application
        run: docker compose up -d